In [12]:
import pandas as pd
df = pd.read_csv('/Users/aidanastridge/Documents/wideloop/32100353.csv')

In [13]:
#Dictionary
dict = {}

In [14]:
#Wideloop function for 'long' data
#wideloop(dataframe,index,columns,values,selector,dictionaryname)
#wideloop(a,b,c,d,e,f)
#a - dataframe: Pandas data frame
#b - index: Descriptors (Year, Month, Day etc.)
#c - columns: Single column becomes multiple columns for each value
#d - values: Values for the columns
#e - selector: Single desicriptor you want to use to analyze
#f - dictionaryname: Dictionary name

def wideloop(dataframe,index,columns,values,selector,dictionaryname):
    df_pivot = (dataframe.pivot(index=index,columns=columns,values=values)
         .sort_index(level=[1,0]))
    df_pivot.reset_index(inplace=True)
    selectors= list(df_pivot[selector].unique())
    for i in selectors:
        dictionaryname[i] = pd.DataFrame(df_pivot.loc[df_pivot[selector] ==  i ])

In [15]:
wideloop(df,['REF_DATE','GEO'],'Estimates','VALUE','GEO',dict)

#dict[''] will procuce the dataframe for selected in quotes
dict['Alberta']

Estimates,REF_DATE,GEO,Average yield per colony,Beekeepers,Colonies,"Production of natural honey, total [16133111]",Value of natural honey and wax,"Value of natural honey, total [16133111]"
0,1924,Alberta,0.0,160.0,0.0,55.0,14.0,14.0
1,1925,Alberta,56.0,140.0,2040.0,115.0,24.0,23.0
2,1926,Alberta,84.0,150.0,2560.0,215.0,38.0,37.0
3,1927,Alberta,87.0,200.0,3450.0,300.0,63.0,60.0
4,1928,Alberta,81.0,200.0,4150.0,336.0,70.0,67.0
...,...,...,...,...,...,...,...,...
94,2018,Alberta,NaN,1572.0,311000.0,38564.0,NaN,66472.0
95,2019,Alberta,NaN,1653.0,314800.0,31418.0,NaN,58188.0
96,2020,Alberta,NaN,1621.0,283000.0,30735.0,NaN,66846.0
97,2021,Alberta,NaN,1754.0,324500.0,34061.0,NaN,93216.0
98,2022,Alberta,NaN,1700.0,300500.0,30407.0,NaN,94706.0